version: '3'
services:
  jenkins-tools:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: seanly/jenkins-job-builder
    restart: unless-stopped
    tty: true
    entrypoint: /bin/bash
    working_dir: /code
    volumes:
      - ./:/code