jobs:
- name: test-job
  type: pipeline
  description: auto-config job
  oesTemplate:
    consoleProvider:
      script: |
        echo "hello"
        echo "${BRANCH_NAME}"
    parameters: |
      ---
      BRANCH_NAME: main